ALTER SESSION SET CONTAINER = FREEPDB1;

CREATE USER CLAIM_USER IDENTIFIED BY "ClaimDb123";
GRANT CREATE SESSION TO CLAIM_USER;
GRANT CREATE TABLE TO CLAIM_USER;
GRANT CREATE SEQUENCE TO CLAIM_USER;
GRANT CREATE VIEW TO CLAIM_USER;
GRANT CREATE PROCEDURE TO CLAIM_USER;
GRANT CREATE TRIGGER TO CLAIM_USER;
ALTER USER CLAIM_USER QUOTA UNLIMITED ON USERS;

CREATE USER POLICY_USER IDENTIFIED BY "PolicyDb123";
GRANT CREATE SESSION TO POLICY_USER;
GRANT CREATE TABLE TO POLICY_USER;
GRANT CREATE SEQUENCE TO POLICY_USER;
GRANT CREATE VIEW TO POLICY_USER;
GRANT CREATE PROCEDURE TO POLICY_USER;
GRANT CREATE TRIGGER TO POLICY_USER;
ALTER USER POLICY_USER QUOTA UNLIMITED ON USERS;

CREATE USER PAYMENT_USER IDENTIFIED BY "PaymentDb123";
GRANT CREATE SESSION TO PAYMENT_USER;
GRANT CREATE TABLE TO PAYMENT_USER;
GRANT CREATE SEQUENCE TO PAYMENT_USER;
GRANT CREATE VIEW TO PAYMENT_USER;
GRANT CREATE PROCEDURE TO PAYMENT_USER;
GRANT CREATE TRIGGER TO PAYMENT_USER;
ALTER USER PAYMENT_USER QUOTA UNLIMITED ON USERS;